//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class access_requirement
    {
        public int mapId { get; set; }
        public byte difficulty { get; set; }
        public byte level_min { get; set; }
        public byte level_max { get; set; }
        public int item_level { get; set; }
        public int item { get; set; }
        public int item2 { get; set; }
        public int quest_done_A { get; set; }
        public int quest_done_H { get; set; }
        public int completed_achievement { get; set; }
        public string quest_failed_text { get; set; }
        public string comment { get; set; }
    }
}
