//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class achievement_dbc
    {
        public long ID { get; set; }
        public int requiredFaction { get; set; }
        public int mapID { get; set; }
        public long points { get; set; }
        public long flags { get; set; }
        public long count { get; set; }
        public long refAchievement { get; set; }
    }
}
