//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class achievement_reward
    {
        public int entry { get; set; }
        public int title_A { get; set; }
        public int title_H { get; set; }
        public int item { get; set; }
        public int sender { get; set; }
        public string subject { get; set; }
        public string text { get; set; }
        public Nullable<int> mailTemplate { get; set; }
    }
}
