//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class broadcast_text
    {
        public int ID { get; set; }
        public int Language { get; set; }
        public string MaleText { get; set; }
        public string FemaleText { get; set; }
        public int EmoteID0 { get; set; }
        public int EmoteID1 { get; set; }
        public int EmoteID2 { get; set; }
        public int EmoteDelay0 { get; set; }
        public int EmoteDelay1 { get; set; }
        public int EmoteDelay2 { get; set; }
        public int SoundId { get; set; }
        public int Unk1 { get; set; }
        public int Unk2 { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
