//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class capital_city_research_data
    {
        public int ResearchSet { get; set; }
        public int Rank { get; set; }
        public int Description { get; set; }
        public int ReqCityRank { get; set; }
        public int ReqItem1 { get; set; }
        public int ReqItem2 { get; set; }
        public int ReqItem3 { get; set; }
        public int ReqItem4 { get; set; }
        public int ReqItemCount1 { get; set; }
        public int ReqItemCount2 { get; set; }
        public int ReqItemCount3 { get; set; }
        public int ReqItemCount4 { get; set; }
        public int QuestSet { get; set; }
        public int Spell { get; set; }
        public int Item { get; set; }
        public int Progress { get; set; }
        public string Comment { get; set; }
    }
}
