//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class capital_city_research_vendor_data
    {
        public int Item { get; set; }
        public int MaxCount { get; set; }
        public int IncrTime { get; set; }
        public int ItemExtendedCost { get; set; }
        public int ReqCityRank { get; set; }
    }
}
