//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_text
    {
        public int entry { get; set; }
        public byte groupid { get; set; }
        public byte id { get; set; }
        public string text { get; set; }
        public byte type { get; set; }
        public byte language { get; set; }
        public float probability { get; set; }
        public int emote { get; set; }
        public int duration { get; set; }
        public int sound { get; set; }
        public int BroadcastTextId { get; set; }
        public byte TextRange { get; set; }
        public string comment { get; set; }
    }
}
