//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_template_addon
    {
        public int entry { get; set; }
        public long path_id { get; set; }
        public int mount { get; set; }
        public long bytes1 { get; set; }
        public long bytes2 { get; set; }
        public int emote { get; set; }
        public string auras { get; set; }
    }
}
