//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_onkill_reputation
    {
        public int creature_id { get; set; }
        public short RewOnKillRepFaction1 { get; set; }
        public short RewOnKillRepFaction2 { get; set; }
        public sbyte MaxStanding1 { get; set; }
        public sbyte IsTeamAward1 { get; set; }
        public int RewOnKillRepValue1 { get; set; }
        public sbyte MaxStanding2 { get; set; }
        public sbyte IsTeamAward2 { get; set; }
        public int RewOnKillRepValue2 { get; set; }
        public byte TeamDependent { get; set; }
    }
}
