//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_template
    {
        public int entry { get; set; }
        public int difficulty_entry_1 { get; set; }
        public int difficulty_entry_2 { get; set; }
        public int difficulty_entry_3 { get; set; }
        public long KillCredit1 { get; set; }
        public long KillCredit2 { get; set; }
        public int modelid1 { get; set; }
        public int modelid2 { get; set; }
        public int modelid3 { get; set; }
        public int modelid4 { get; set; }
        public string name { get; set; }
        public string subname { get; set; }
        public string IconName { get; set; }
        public int gossip_menu_id { get; set; }
        public byte minlevel { get; set; }
        public byte maxlevel { get; set; }
        public short exp { get; set; }
        public int faction { get; set; }
        public long npcflag { get; set; }
        public float speed_walk { get; set; }
        public float speed_run { get; set; }
        public float scale { get; set; }
        public byte rank { get; set; }
        public sbyte dmgschool { get; set; }
        public long BaseAttackTime { get; set; }
        public long RangeAttackTime { get; set; }
        public float BaseVariance { get; set; }
        public float RangeVariance { get; set; }
        public byte unit_class { get; set; }
        public long unit_flags { get; set; }
        public long unit_flags2 { get; set; }
        public long dynamicflags { get; set; }
        public sbyte family { get; set; }
        public sbyte trainer_type { get; set; }
        public int trainer_spell { get; set; }
        public byte trainer_class { get; set; }
        public byte trainer_race { get; set; }
        public byte type { get; set; }
        public long type_flags { get; set; }
        public int lootid { get; set; }
        public int pickpocketloot { get; set; }
        public int skinloot { get; set; }
        public short resistance1 { get; set; }
        public short resistance2 { get; set; }
        public short resistance3 { get; set; }
        public short resistance4 { get; set; }
        public short resistance5 { get; set; }
        public short resistance6 { get; set; }
        public int spell1 { get; set; }
        public int spell2 { get; set; }
        public int spell3 { get; set; }
        public int spell4 { get; set; }
        public int spell5 { get; set; }
        public int spell6 { get; set; }
        public int spell7 { get; set; }
        public int spell8 { get; set; }
        public int PetSpellDataId { get; set; }
        public int VehicleId { get; set; }
        public int mingold { get; set; }
        public int maxgold { get; set; }
        public string AIName { get; set; }
        public byte MovementType { get; set; }
        public byte InhabitType { get; set; }
        public float HoverHeight { get; set; }
        public float HealthModifier { get; set; }
        public float ManaModifier { get; set; }
        public float ArmorModifier { get; set; }
        public float DamageModifier { get; set; }
        public float ExperienceModifier { get; set; }
        public byte RacialLeader { get; set; }
        public long questItem1 { get; set; }
        public long questItem2 { get; set; }
        public long questItem3 { get; set; }
        public long questItem4 { get; set; }
        public long questItem5 { get; set; }
        public long questItem6 { get; set; }
        public long movementId { get; set; }
        public byte RegenHealth { get; set; }
        public long mechanic_immune_mask { get; set; }
        public long flags_extra { get; set; }
        public int WarSchool { get; set; }
        public string ScriptName { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
