//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_classlevelstats
    {
        public byte level { get; set; }
        public byte @class { get; set; }
        public int basehp0 { get; set; }
        public int basehp1 { get; set; }
        public int basehp2 { get; set; }
        public int basemana { get; set; }
        public int basearmor { get; set; }
        public int attackpower { get; set; }
        public int rangedattackpower { get; set; }
        public float damage_base { get; set; }
        public float damage_exp1 { get; set; }
        public float damage_exp2 { get; set; }
        public string comment { get; set; }
    }
}
