//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbc_achivement_category
    {
        public int ID { get; set; }
        public int ParentID { get; set; }
        public string Name_loc1 { get; set; }
        public string Name_loc2 { get; set; }
        public string Name_loc3 { get; set; }
        public string Name_loc4 { get; set; }
        public string Name_loc5 { get; set; }
        public string Name_loc6 { get; set; }
        public string Name_loc7 { get; set; }
        public string Name_loc8 { get; set; }
        public string Name_loc9 { get; set; }
        public string Name_loc10 { get; set; }
        public string Name_loc11 { get; set; }
        public string Name_loc12 { get; set; }
        public string Name_loc13 { get; set; }
        public string Name_loc14 { get; set; }
        public string Name_loc15 { get; set; }
        public string Name_loc16 { get; set; }
        public int NameDisplayFlag { get; set; }
        public int DisplayOrder { get; set; }
    }
}
