//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbc_achievement
    {
        public int ID { get; set; }
        public int Faction { get; set; }
        public int Map { get; set; }
        public int Previous { get; set; }
        public string Name_loc1 { get; set; }
        public string Name_loc2 { get; set; }
        public string Name_loc3 { get; set; }
        public string Name_loc4 { get; set; }
        public string Name_loc5 { get; set; }
        public string Name_loc6 { get; set; }
        public string Name_loc7 { get; set; }
        public string Name_loc8 { get; set; }
        public string Name_loc9 { get; set; }
        public string Name_loc10 { get; set; }
        public string Name_loc11 { get; set; }
        public string Name_loc12 { get; set; }
        public string Name_loc13 { get; set; }
        public string Name_loc14 { get; set; }
        public string Name_loc15 { get; set; }
        public string Name_loc16 { get; set; }
        public int NameDisplayFlag { get; set; }
        public string Description_loc1 { get; set; }
        public string Description_loc2 { get; set; }
        public string Description_loc3 { get; set; }
        public string Description_loc4 { get; set; }
        public string Description_loc5 { get; set; }
        public string Description_loc6 { get; set; }
        public string Description_loc7 { get; set; }
        public string Description_loc8 { get; set; }
        public string Description_loc9 { get; set; }
        public string Description_loc10 { get; set; }
        public string Description_loc11 { get; set; }
        public string Description_loc12 { get; set; }
        public string Description_loc13 { get; set; }
        public string Description_loc14 { get; set; }
        public string Description_loc15 { get; set; }
        public string Description_loc16 { get; set; }
        public int DescriptionDisplayFlag { get; set; }
        public int Category { get; set; }
        public int Points { get; set; }
        public int Unknown41 { get; set; }
        public int Unknown42 { get; set; }
        public int SpellIcon { get; set; }
        public string Reward_loc1 { get; set; }
        public string Reward_loc2 { get; set; }
        public string Reward_loc3 { get; set; }
        public string Reward_loc4 { get; set; }
        public string Reward_loc5 { get; set; }
        public string Reward_loc6 { get; set; }
        public string Reward_loc7 { get; set; }
        public string Reward_loc8 { get; set; }
        public string Reward_loc9 { get; set; }
        public string Reward_loc10 { get; set; }
        public string Reward_loc11 { get; set; }
        public string Reward_loc12 { get; set; }
        public string Reward_loc13 { get; set; }
        public string Reward_loc14 { get; set; }
        public string Reward_loc15 { get; set; }
        public string Reward_loc16 { get; set; }
        public int RewardDisplayFlag { get; set; }
        public int Unknown61 { get; set; }
        public int Unknown62 { get; set; }
    }
}
