//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbc_item
    {
        public long Entry { get; set; }
        public long Class { get; set; }
        public long SubClass { get; set; }
        public int SoundOverrideSubClass { get; set; }
        public int Material { get; set; }
        public long DisplayID { get; set; }
        public long InventoryType { get; set; }
        public long Sheath { get; set; }
    }
}
