//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbc_itemset
    {
        public int id { get; set; }
        public string name { get; set; }
        public int flags { get; set; }
        public int item1 { get; set; }
        public int item2 { get; set; }
        public int item3 { get; set; }
        public int item4 { get; set; }
        public int item5 { get; set; }
        public int item6 { get; set; }
        public int item7 { get; set; }
        public int item8 { get; set; }
        public int item9 { get; set; }
        public int item10 { get; set; }
        public int item11 { get; set; }
        public int item12 { get; set; }
        public int item13 { get; set; }
        public int item14 { get; set; }
        public int item15 { get; set; }
        public int item16 { get; set; }
        public int item17 { get; set; }
        public int spell1 { get; set; }
        public int spell2 { get; set; }
        public int spell3 { get; set; }
        public int spell4 { get; set; }
        public int spell5 { get; set; }
        public int spell6 { get; set; }
        public int spell7 { get; set; }
        public int spell8 { get; set; }
        public int set1 { get; set; }
        public int set2 { get; set; }
        public int set3 { get; set; }
        public int set4 { get; set; }
        public int set5 { get; set; }
        public int set6 { get; set; }
        public int set7 { get; set; }
        public int set8 { get; set; }
        public int skill { get; set; }
        public int skillvalue { get; set; }
    }
}
