//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbc_talent
    {
        public int ID { get; set; }
        public int Tab { get; set; }
        public int Row { get; set; }
        public int Column { get; set; }
        public int Rank1 { get; set; }
        public int Rank2 { get; set; }
        public int Rank3 { get; set; }
        public int Rank4 { get; set; }
        public int Rank5 { get; set; }
        public int Rank6 { get; set; }
        public int Rank7 { get; set; }
        public int Rank8 { get; set; }
        public int Rank9 { get; set; }
        public int PrereqTalent1 { get; set; }
        public int PrereqTalent2 { get; set; }
        public int PrereqTalent3 { get; set; }
        public int PrereqTalentCount1 { get; set; }
        public int PrereqTalentCount2 { get; set; }
        public int PrereqTalentCount3 { get; set; }
        public int IsAbility { get; set; }
        public int ReqSpellID { get; set; }
        public long PetFlagsA { get; set; }
        public long PetFlagsB { get; set; }
    }
}
