//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbc_skilllineability
    {
        public long ID { get; set; }
        public int SkillLine { get; set; }
        public int SpellEntry { get; set; }
        public int Race { get; set; }
        public int Class { get; set; }
        public Nullable<int> ExcludeRace { get; set; }
        public Nullable<int> ExcludeClass { get; set; }
        public int RequiredSkillValue { get; set; }
        public int SupercededBySpell { get; set; }
        public int AcquiredMethod { get; set; }
        public int SkillLineRankHigh { get; set; }
        public int SkillLineRankLow { get; set; }
        public Nullable<int> CharacterPoints { get; set; }
        public Nullable<int> NumSkillUps { get; set; }
    }
}
