//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbc_spell_visual
    {
        public int ID { get; set; }
        public int Precast { get; set; }
        public int Cast { get; set; }
        public int Impact { get; set; }
        public int State { get; set; }
        public int StateDone { get; set; }
        public int Channel { get; set; }
        public int HasMissile { get; set; }
        public int MissileModel { get; set; }
        public int MissilePathType { get; set; }
        public int MissileDestinationAttachPoint { get; set; }
        public int MissileSound { get; set; }
        public int AnimEventSound { get; set; }
        public int Flag { get; set; }
        public int CasterImpact { get; set; }
        public int TargetImpact { get; set; }
        public int MissileAttachment { get; set; }
        public int MissileFollowGroundHight { get; set; }
        public int MissileFollowGroundDropSpeed { get; set; }
        public int MissileFollowGroundApproach { get; set; }
        public int MissileFollowGroundFlags { get; set; }
        public int MissileMotion { get; set; }
        public int MissileTargetKit { get; set; }
        public int InstantAreaKit { get; set; }
        public int ImpactAreaKit { get; set; }
        public int PersistentAreaKit { get; set; }
        public int MissileCastOffsetX { get; set; }
        public int MissileCastOffsetY { get; set; }
        public int MissileCastOffsetZ { get; set; }
        public int MissileImpactOffsetX { get; set; }
        public int MissileImpactOffsetY { get; set; }
        public int MissileImpactOffsetZ { get; set; }
    }
}
