//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbc_spell_item_enchantment
    {
        public int ID { get; set; }
        public int Charges { get; set; }
        public int EnchantType1 { get; set; }
        public int EnchantType2 { get; set; }
        public int EnchantType3 { get; set; }
        public int MinValue1 { get; set; }
        public int MinValue2 { get; set; }
        public int MinValue3 { get; set; }
        public int MaxValue1 { get; set; }
        public int MaxValue2 { get; set; }
        public int MaxValue3 { get; set; }
        public int EnchantObject1 { get; set; }
        public int EnchantObject2 { get; set; }
        public int EnchantObject3 { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Name4 { get; set; }
        public string Name5 { get; set; }
        public string Name6 { get; set; }
        public string Name7 { get; set; }
        public string Name8 { get; set; }
        public string Name9 { get; set; }
        public string Name10 { get; set; }
        public string Name11 { get; set; }
        public string Name12 { get; set; }
        public string Name13 { get; set; }
        public string Name14 { get; set; }
        public string Name15 { get; set; }
        public string Name16 { get; set; }
        public long NameFlag { get; set; }
        public int EnchantVisual { get; set; }
        public int EnchantFlag { get; set; }
        public int ItemCache { get; set; }
        public int EnchantCondition { get; set; }
        public int SkillLine { get; set; }
        public int SkillValue { get; set; }
        public int RequiredLevel { get; set; }
    }
}
