//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbc_achievement_criteria
    {
        public int ID { get; set; }
        public int Achievement { get; set; }
        public int Type { get; set; }
        public int AssetID { get; set; }
        public int Quantity { get; set; }
        public int StartEvent { get; set; }
        public int StartAsset { get; set; }
        public int FailEvent { get; set; }
        public int FailAsset { get; set; }
        public string Description_loc1 { get; set; }
        public string Description_loc2 { get; set; }
        public string Description_loc3 { get; set; }
        public string Description_loc4 { get; set; }
        public string Description_loc5 { get; set; }
        public string Description_loc6 { get; set; }
        public string Description_loc7 { get; set; }
        public string Description_loc8 { get; set; }
        public string Description_loc9 { get; set; }
        public string Description_loc10 { get; set; }
        public string Description_loc11 { get; set; }
        public string Description_loc12 { get; set; }
        public string Description_loc13 { get; set; }
        public string Description_loc14 { get; set; }
        public string Description_loc15 { get; set; }
        public string Description_loc16 { get; set; }
        public int DescriptionDisplayFlag { get; set; }
        public int Flags { get; set; }
        public int TimerStartEvent { get; set; }
        public int TimerAssetID { get; set; }
        public int TimerTime { get; set; }
        public int DisplayOrder { get; set; }
    }
}
