//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_scripts
    {
        public int id { get; set; }
        public long delay { get; set; }
        public int command { get; set; }
        public int datalong { get; set; }
        public long datalong2 { get; set; }
        public int dataint { get; set; }
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }
        public float o { get; set; }
    }
}
