//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_event_npc_vendor
    {
        public sbyte eventEntry { get; set; }
        public int guid { get; set; }
        public short slot { get; set; }
        public int item { get; set; }
        public int maxcount { get; set; }
        public int incrtime { get; set; }
        public int ExtendedCost { get; set; }
        public int ReqCityRank { get; set; }
    }
}
