//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_weather
    {
        public int zone { get; set; }
        public byte spring_rain_chance { get; set; }
        public byte spring_snow_chance { get; set; }
        public byte spring_storm_chance { get; set; }
        public byte summer_rain_chance { get; set; }
        public byte summer_snow_chance { get; set; }
        public byte summer_storm_chance { get; set; }
        public byte fall_rain_chance { get; set; }
        public byte fall_snow_chance { get; set; }
        public byte fall_storm_chance { get; set; }
        public byte winter_rain_chance { get; set; }
        public byte winter_snow_chance { get; set; }
        public byte winter_storm_chance { get; set; }
        public string ScriptName { get; set; }
    }
}
