//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_event_condition
    {
        public byte eventEntry { get; set; }
        public int condition_id { get; set; }
        public Nullable<float> req_num { get; set; }
        public int max_world_state_field { get; set; }
        public int done_world_state_field { get; set; }
        public string description { get; set; }
    }
}
