//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameobject_template
    {
        public int entry { get; set; }
        public byte type { get; set; }
        public int displayId { get; set; }
        public string name { get; set; }
        public string IconName { get; set; }
        public string castBarCaption { get; set; }
        public string unk1 { get; set; }
        public int faction { get; set; }
        public long flags { get; set; }
        public float size { get; set; }
        public long questItem1 { get; set; }
        public long questItem2 { get; set; }
        public long questItem3 { get; set; }
        public long questItem4 { get; set; }
        public long questItem5 { get; set; }
        public long questItem6 { get; set; }
        public long data0 { get; set; }
        public int data1 { get; set; }
        public long data2 { get; set; }
        public long data3 { get; set; }
        public long data4 { get; set; }
        public long data5 { get; set; }
        public int data6 { get; set; }
        public long data7 { get; set; }
        public long data8 { get; set; }
        public long data9 { get; set; }
        public long data10 { get; set; }
        public long data11 { get; set; }
        public long data12 { get; set; }
        public long data13 { get; set; }
        public long data14 { get; set; }
        public long data15 { get; set; }
        public long data16 { get; set; }
        public long data17 { get; set; }
        public long data18 { get; set; }
        public long data19 { get; set; }
        public long data20 { get; set; }
        public long data21 { get; set; }
        public long data22 { get; set; }
        public long data23 { get; set; }
        public string AIName { get; set; }
        public string ScriptName { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
