//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameobject
    {
        public long guid { get; set; }
        public int id { get; set; }
        public int map { get; set; }
        public int zoneId { get; set; }
        public int areaId { get; set; }
        public byte spawnMask { get; set; }
        public long phaseMask { get; set; }
        public float position_x { get; set; }
        public float position_y { get; set; }
        public float position_z { get; set; }
        public float orientation { get; set; }
        public float rotation0 { get; set; }
        public float rotation1 { get; set; }
        public float rotation2 { get; set; }
        public float rotation3 { get; set; }
        public int spawntimesecs { get; set; }
        public byte animprogress { get; set; }
        public byte state { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
