//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class gossip_menu_option
    {
        public int menu_id { get; set; }
        public int id { get; set; }
        public int option_icon { get; set; }
        public int OptionBroadcastTextID { get; set; }
        public byte option_id { get; set; }
        public long npc_option_npcflag { get; set; }
        public int action_menu_id { get; set; }
        public int action_poi_id { get; set; }
        public byte box_coded { get; set; }
        public int box_money { get; set; }
        public int BoxBroadcastTextID { get; set; }
        public byte SingleTimeCheck { get; set; }
    }
}
