//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_template
    {
        public int entry { get; set; }
        public byte @class { get; set; }
        public byte subclass { get; set; }
        public sbyte SoundOverrideSubclass { get; set; }
        public string name { get; set; }
        public int displayid { get; set; }
        public byte Quality { get; set; }
        public long Flags { get; set; }
        public long FlagsExtra { get; set; }
        public byte BuyCount { get; set; }
        public long BuyPrice { get; set; }
        public long SellPrice { get; set; }
        public byte InventoryType { get; set; }
        public int AllowableClass { get; set; }
        public int AllowableRace { get; set; }
        public int ItemLevel { get; set; }
        public byte RequiredLevel { get; set; }
        public int RequiredSkill { get; set; }
        public int RequiredSkillRank { get; set; }
        public int requiredspell { get; set; }
        public int requiredhonorrank { get; set; }
        public int RequiredCityRank { get; set; }
        public int RequiredReputationFaction { get; set; }
        public int RequiredReputationRank { get; set; }
        public int maxcount { get; set; }
        public int stackable { get; set; }
        public byte ContainerSlots { get; set; }
        public byte StatsCount { get; set; }
        public byte stat_type1 { get; set; }
        public short stat_value1 { get; set; }
        public byte stat_type2 { get; set; }
        public short stat_value2 { get; set; }
        public byte stat_type3 { get; set; }
        public short stat_value3 { get; set; }
        public byte stat_type4 { get; set; }
        public short stat_value4 { get; set; }
        public byte stat_type5 { get; set; }
        public short stat_value5 { get; set; }
        public byte stat_type6 { get; set; }
        public short stat_value6 { get; set; }
        public byte stat_type7 { get; set; }
        public short stat_value7 { get; set; }
        public byte stat_type8 { get; set; }
        public short stat_value8 { get; set; }
        public byte stat_type9 { get; set; }
        public short stat_value9 { get; set; }
        public byte stat_type10 { get; set; }
        public short stat_value10 { get; set; }
        public short ScalingStatDistribution { get; set; }
        public long ScalingStatValue { get; set; }
        public float dmg_min1 { get; set; }
        public float dmg_max1 { get; set; }
        public byte dmg_type1 { get; set; }
        public float dmg_min2 { get; set; }
        public float dmg_max2 { get; set; }
        public byte dmg_type2 { get; set; }
        public int armor { get; set; }
        public byte holy_res { get; set; }
        public byte fire_res { get; set; }
        public byte nature_res { get; set; }
        public byte frost_res { get; set; }
        public byte shadow_res { get; set; }
        public byte arcane_res { get; set; }
        public int delay { get; set; }
        public byte ammo_type { get; set; }
        public float RangedModRange { get; set; }
        public int spellid_1 { get; set; }
        public byte spelltrigger_1 { get; set; }
        public short spellcharges_1 { get; set; }
        public float spellppmRate_1 { get; set; }
        public int spellcooldown_1 { get; set; }
        public int spellcategory_1 { get; set; }
        public int spellcategorycooldown_1 { get; set; }
        public int spellid_2 { get; set; }
        public byte spelltrigger_2 { get; set; }
        public short spellcharges_2 { get; set; }
        public float spellppmRate_2 { get; set; }
        public int spellcooldown_2 { get; set; }
        public int spellcategory_2 { get; set; }
        public int spellcategorycooldown_2 { get; set; }
        public int spellid_3 { get; set; }
        public byte spelltrigger_3 { get; set; }
        public short spellcharges_3 { get; set; }
        public float spellppmRate_3 { get; set; }
        public int spellcooldown_3 { get; set; }
        public int spellcategory_3 { get; set; }
        public int spellcategorycooldown_3 { get; set; }
        public int spellid_4 { get; set; }
        public byte spelltrigger_4 { get; set; }
        public short spellcharges_4 { get; set; }
        public float spellppmRate_4 { get; set; }
        public int spellcooldown_4 { get; set; }
        public int spellcategory_4 { get; set; }
        public int spellcategorycooldown_4 { get; set; }
        public int spellid_5 { get; set; }
        public byte spelltrigger_5 { get; set; }
        public short spellcharges_5 { get; set; }
        public float spellppmRate_5 { get; set; }
        public int spellcooldown_5 { get; set; }
        public int spellcategory_5 { get; set; }
        public int spellcategorycooldown_5 { get; set; }
        public byte bonding { get; set; }
        public string description { get; set; }
        public int PageText { get; set; }
        public byte LanguageID { get; set; }
        public byte PageMaterial { get; set; }
        public int startquest { get; set; }
        public int lockid { get; set; }
        public sbyte Material { get; set; }
        public byte sheath { get; set; }
        public int RandomProperty { get; set; }
        public int RandomSuffix { get; set; }
        public int block { get; set; }
        public int itemset { get; set; }
        public int MaxDurability { get; set; }
        public int area { get; set; }
        public short Map { get; set; }
        public int BagFamily { get; set; }
        public int TotemCategory { get; set; }
        public sbyte socketColor_1 { get; set; }
        public int socketContent_1 { get; set; }
        public sbyte socketColor_2 { get; set; }
        public int socketContent_2 { get; set; }
        public sbyte socketColor_3 { get; set; }
        public int socketContent_3 { get; set; }
        public int socketBonus { get; set; }
        public int GemProperties { get; set; }
        public short RequiredDisenchantSkill { get; set; }
        public float ArmorDamageModifier { get; set; }
        public long duration { get; set; }
        public short ItemLimitCategory { get; set; }
        public long HolidayId { get; set; }
        public string ScriptName { get; set; }
        public int DisenchantID { get; set; }
        public byte FoodType { get; set; }
        public long minMoneyLoot { get; set; }
        public long maxMoneyLoot { get; set; }
        public long flagsCustom { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
