//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LegacyDataEntities : DbContext
    {
        public LegacyDataEntities()
            : base("name=LegacyDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dbc_achievement> dbc_achievement { get; set; }
        public DbSet<dbc_achievement_criteria> dbc_achievement_criteria { get; set; }
        public DbSet<dbc_achivement_category> dbc_achivement_category { get; set; }
        public DbSet<dbc_item> dbc_item { get; set; }
        public DbSet<dbc_itemset> dbc_itemset { get; set; }
        public DbSet<dbc_skilllineability> dbc_skilllineability { get; set; }
        public DbSet<dbc_spell> dbc_spell { get; set; }
        public DbSet<dbc_spell_item_enchantment> dbc_spell_item_enchantment { get; set; }
        public DbSet<dbc_spell_obs> dbc_spell_obs { get; set; }
        public DbSet<dbc_spell_original> dbc_spell_original { get; set; }
        public DbSet<dbc_spell_visual> dbc_spell_visual { get; set; }
        public DbSet<dbc_talent> dbc_talent { get; set; }
        public DbSet<define_gossip_icon> define_gossip_icon { get; set; }
        public DbSet<define_item_ammo_type> define_item_ammo_type { get; set; }
        public DbSet<define_item_bonding> define_item_bonding { get; set; }
        public DbSet<define_item_damage_type> define_item_damage_type { get; set; }
        public DbSet<define_item_group_sound> define_item_group_sound { get; set; }
        public DbSet<define_item_inventory_type> define_item_inventory_type { get; set; }
        public DbSet<define_item_material> define_item_material { get; set; }
        public DbSet<define_item_quality> define_item_quality { get; set; }
        public DbSet<define_item_sheath> define_item_sheath { get; set; }
        public DbSet<define_item_socket_color> define_item_socket_color { get; set; }
        public DbSet<define_item_spell_trigger> define_item_spell_trigger { get; set; }
        public DbSet<define_item_stat_type> define_item_stat_type { get; set; }
        public DbSet<define_menu_option_type> define_menu_option_type { get; set; }
        public DbSet<define_reputation_rank> define_reputation_rank { get; set; }
        public DbSet<define_smart_script_action> define_smart_script_action { get; set; }
        public DbSet<define_smart_script_event> define_smart_script_event { get; set; }
        public DbSet<define_smart_script_target> define_smart_script_target { get; set; }
        public DbSet<define_spell_aura> define_spell_aura { get; set; }
        public DbSet<define_spell_aura_state> define_spell_aura_state { get; set; }
        public DbSet<define_spell_damage_class> define_spell_damage_class { get; set; }
        public DbSet<define_spell_effect> define_spell_effect { get; set; }
        public DbSet<define_spell_family> define_spell_family { get; set; }
        public DbSet<define_spell_implicit_target> define_spell_implicit_target { get; set; }
        public DbSet<define_spell_item_enchantment_type> define_spell_item_enchantment_type { get; set; }
        public DbSet<define_spell_power_type> define_spell_power_type { get; set; }
        public DbSet<define_talent_tab> define_talent_tab { get; set; }
        public DbSet<spell_v4> spell_v4 { get; set; }
    }
}
