//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class locales_gossip_menu_option
    {
        public int menu_id { get; set; }
        public int id { get; set; }
        public string option_text_loc1 { get; set; }
        public string option_text_loc2 { get; set; }
        public string option_text_loc3 { get; set; }
        public string option_text_loc4 { get; set; }
        public string option_text_loc5 { get; set; }
        public string option_text_loc6 { get; set; }
        public string option_text_loc7 { get; set; }
        public string option_text_loc8 { get; set; }
        public string box_text_loc1 { get; set; }
        public string box_text_loc2 { get; set; }
        public string box_text_loc3 { get; set; }
        public string box_text_loc4 { get; set; }
        public string box_text_loc5 { get; set; }
        public string box_text_loc6 { get; set; }
        public string box_text_loc7 { get; set; }
        public string box_text_loc8 { get; set; }
    }
}
