//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class locales_broadcast_text
    {
        public int ID { get; set; }
        public string MaleText_loc1 { get; set; }
        public string MaleText_loc2 { get; set; }
        public string MaleText_loc3 { get; set; }
        public string MaleText_loc4 { get; set; }
        public string MaleText_loc5 { get; set; }
        public string MaleText_loc6 { get; set; }
        public string MaleText_loc7 { get; set; }
        public string MaleText_loc8 { get; set; }
        public string FemaleText_loc1 { get; set; }
        public string FemaleText_loc2 { get; set; }
        public string FemaleText_loc3 { get; set; }
        public string FemaleText_loc4 { get; set; }
        public string FemaleText_loc5 { get; set; }
        public string FemaleText_loc6 { get; set; }
        public string FemaleText_loc7 { get; set; }
        public string FemaleText_loc8 { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
