//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class locales_points_of_interest
    {
        public int entry { get; set; }
        public string icon_name_loc1 { get; set; }
        public string icon_name_loc2 { get; set; }
        public string icon_name_loc3 { get; set; }
        public string icon_name_loc4 { get; set; }
        public string icon_name_loc5 { get; set; }
        public string icon_name_loc6 { get; set; }
        public string icon_name_loc7 { get; set; }
        public string icon_name_loc8 { get; set; }
    }
}
