//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class locales_npc_text
    {
        public int ID { get; set; }
        public string Text0_0_loc1 { get; set; }
        public string Text0_0_loc2 { get; set; }
        public string Text0_0_loc3 { get; set; }
        public string Text0_0_loc4 { get; set; }
        public string Text0_0_loc5 { get; set; }
        public string Text0_0_loc6 { get; set; }
        public string Text0_0_loc7 { get; set; }
        public string Text0_0_loc8 { get; set; }
        public string Text0_1_loc1 { get; set; }
        public string Text0_1_loc2 { get; set; }
        public string Text0_1_loc3 { get; set; }
        public string Text0_1_loc4 { get; set; }
        public string Text0_1_loc5 { get; set; }
        public string Text0_1_loc6 { get; set; }
        public string Text0_1_loc7 { get; set; }
        public string Text0_1_loc8 { get; set; }
        public string Text1_0_loc1 { get; set; }
        public string Text1_0_loc2 { get; set; }
        public string Text1_0_loc3 { get; set; }
        public string Text1_0_loc4 { get; set; }
        public string Text1_0_loc5 { get; set; }
        public string Text1_0_loc6 { get; set; }
        public string Text1_0_loc7 { get; set; }
        public string Text1_0_loc8 { get; set; }
        public string Text1_1_loc1 { get; set; }
        public string Text1_1_loc2 { get; set; }
        public string Text1_1_loc3 { get; set; }
        public string Text1_1_loc4 { get; set; }
        public string Text1_1_loc5 { get; set; }
        public string Text1_1_loc6 { get; set; }
        public string Text1_1_loc7 { get; set; }
        public string Text1_1_loc8 { get; set; }
        public string Text2_0_loc1 { get; set; }
        public string Text2_0_loc2 { get; set; }
        public string Text2_0_loc3 { get; set; }
        public string Text2_0_loc4 { get; set; }
        public string Text2_0_loc5 { get; set; }
        public string Text2_0_loc6 { get; set; }
        public string Text2_0_loc7 { get; set; }
        public string Text2_0_loc8 { get; set; }
        public string Text2_1_loc1 { get; set; }
        public string Text2_1_loc2 { get; set; }
        public string Text2_1_loc3 { get; set; }
        public string Text2_1_loc4 { get; set; }
        public string Text2_1_loc5 { get; set; }
        public string Text2_1_loc6 { get; set; }
        public string Text2_1_loc7 { get; set; }
        public string Text2_1_loc8 { get; set; }
        public string Text3_0_loc1 { get; set; }
        public string Text3_0_loc2 { get; set; }
        public string Text3_0_loc3 { get; set; }
        public string Text3_0_loc4 { get; set; }
        public string Text3_0_loc5 { get; set; }
        public string Text3_0_loc6 { get; set; }
        public string Text3_0_loc7 { get; set; }
        public string Text3_0_loc8 { get; set; }
        public string Text3_1_loc1 { get; set; }
        public string Text3_1_loc2 { get; set; }
        public string Text3_1_loc3 { get; set; }
        public string Text3_1_loc4 { get; set; }
        public string Text3_1_loc5 { get; set; }
        public string Text3_1_loc6 { get; set; }
        public string Text3_1_loc7 { get; set; }
        public string Text3_1_loc8 { get; set; }
        public string Text4_0_loc1 { get; set; }
        public string Text4_0_loc2 { get; set; }
        public string Text4_0_loc3 { get; set; }
        public string Text4_0_loc4 { get; set; }
        public string Text4_0_loc5 { get; set; }
        public string Text4_0_loc6 { get; set; }
        public string Text4_0_loc7 { get; set; }
        public string Text4_0_loc8 { get; set; }
        public string Text4_1_loc1 { get; set; }
        public string Text4_1_loc2 { get; set; }
        public string Text4_1_loc3 { get; set; }
        public string Text4_1_loc4 { get; set; }
        public string Text4_1_loc5 { get; set; }
        public string Text4_1_loc6 { get; set; }
        public string Text4_1_loc7 { get; set; }
        public string Text4_1_loc8 { get; set; }
        public string Text5_0_loc1 { get; set; }
        public string Text5_0_loc2 { get; set; }
        public string Text5_0_loc3 { get; set; }
        public string Text5_0_loc4 { get; set; }
        public string Text5_0_loc5 { get; set; }
        public string Text5_0_loc6 { get; set; }
        public string Text5_0_loc7 { get; set; }
        public string Text5_0_loc8 { get; set; }
        public string Text5_1_loc1 { get; set; }
        public string Text5_1_loc2 { get; set; }
        public string Text5_1_loc3 { get; set; }
        public string Text5_1_loc4 { get; set; }
        public string Text5_1_loc5 { get; set; }
        public string Text5_1_loc6 { get; set; }
        public string Text5_1_loc7 { get; set; }
        public string Text5_1_loc8 { get; set; }
        public string Text6_0_loc1 { get; set; }
        public string Text6_0_loc2 { get; set; }
        public string Text6_0_loc3 { get; set; }
        public string Text6_0_loc4 { get; set; }
        public string Text6_0_loc5 { get; set; }
        public string Text6_0_loc6 { get; set; }
        public string Text6_0_loc7 { get; set; }
        public string Text6_0_loc8 { get; set; }
        public string Text6_1_loc1 { get; set; }
        public string Text6_1_loc2 { get; set; }
        public string Text6_1_loc3 { get; set; }
        public string Text6_1_loc4 { get; set; }
        public string Text6_1_loc5 { get; set; }
        public string Text6_1_loc6 { get; set; }
        public string Text6_1_loc7 { get; set; }
        public string Text6_1_loc8 { get; set; }
        public string Text7_0_loc1 { get; set; }
        public string Text7_0_loc2 { get; set; }
        public string Text7_0_loc3 { get; set; }
        public string Text7_0_loc4 { get; set; }
        public string Text7_0_loc5 { get; set; }
        public string Text7_0_loc6 { get; set; }
        public string Text7_0_loc7 { get; set; }
        public string Text7_0_loc8 { get; set; }
        public string Text7_1_loc1 { get; set; }
        public string Text7_1_loc2 { get; set; }
        public string Text7_1_loc3 { get; set; }
        public string Text7_1_loc4 { get; set; }
        public string Text7_1_loc5 { get; set; }
        public string Text7_1_loc6 { get; set; }
        public string Text7_1_loc7 { get; set; }
        public string Text7_1_loc8 { get; set; }
    }
}
