//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_text
    {
        public int ID { get; set; }
        public int BroadcastTextID0 { get; set; }
        public float prob0 { get; set; }
        public int BroadcastTextID1 { get; set; }
        public float prob1 { get; set; }
        public int BroadcastTextID2 { get; set; }
        public float prob2 { get; set; }
        public int BroadcastTextID3 { get; set; }
        public float prob3 { get; set; }
        public int BroadcastTextID4 { get; set; }
        public float prob4 { get; set; }
        public int BroadcastTextID5 { get; set; }
        public float prob5 { get; set; }
        public int BroadcastTextID6 { get; set; }
        public float prob6 { get; set; }
        public int BroadcastTextID7 { get; set; }
        public float prob7 { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
