//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_trainer
    {
        public int entry { get; set; }
        public int spell { get; set; }
        public long spellcost { get; set; }
        public int reqskill { get; set; }
        public int reqskillvalue { get; set; }
        public byte reqlevel { get; set; }
        public int reqcityrank { get; set; }
    }
}
