//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_spellclick_spells
    {
        public long npc_entry { get; set; }
        public long spell_id { get; set; }
        public byte cast_flags { get; set; }
        public int user_type { get; set; }
    }
}
