//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_text
    {
        public int ID { get; set; }
        public string text0_0 { get; set; }
        public string text0_1 { get; set; }
        public int BroadcastTextID0 { get; set; }
        public byte lang0 { get; set; }
        public float prob0 { get; set; }
        public int em0_0 { get; set; }
        public int em0_1 { get; set; }
        public int em0_2 { get; set; }
        public int em0_3 { get; set; }
        public int em0_4 { get; set; }
        public int em0_5 { get; set; }
        public string text1_0 { get; set; }
        public string text1_1 { get; set; }
        public int BroadcastTextID1 { get; set; }
        public byte lang1 { get; set; }
        public float prob1 { get; set; }
        public int em1_0 { get; set; }
        public int em1_1 { get; set; }
        public int em1_2 { get; set; }
        public int em1_3 { get; set; }
        public int em1_4 { get; set; }
        public int em1_5 { get; set; }
        public string text2_0 { get; set; }
        public string text2_1 { get; set; }
        public int BroadcastTextID2 { get; set; }
        public byte lang2 { get; set; }
        public float prob2 { get; set; }
        public int em2_0 { get; set; }
        public int em2_1 { get; set; }
        public int em2_2 { get; set; }
        public int em2_3 { get; set; }
        public int em2_4 { get; set; }
        public int em2_5 { get; set; }
        public string text3_0 { get; set; }
        public string text3_1 { get; set; }
        public int BroadcastTextID3 { get; set; }
        public byte lang3 { get; set; }
        public float prob3 { get; set; }
        public int em3_0 { get; set; }
        public int em3_1 { get; set; }
        public int em3_2 { get; set; }
        public int em3_3 { get; set; }
        public int em3_4 { get; set; }
        public int em3_5 { get; set; }
        public string text4_0 { get; set; }
        public string text4_1 { get; set; }
        public int BroadcastTextID4 { get; set; }
        public byte lang4 { get; set; }
        public float prob4 { get; set; }
        public int em4_0 { get; set; }
        public int em4_1 { get; set; }
        public int em4_2 { get; set; }
        public int em4_3 { get; set; }
        public int em4_4 { get; set; }
        public int em4_5 { get; set; }
        public string text5_0 { get; set; }
        public string text5_1 { get; set; }
        public int BroadcastTextID5 { get; set; }
        public byte lang5 { get; set; }
        public float prob5 { get; set; }
        public int em5_0 { get; set; }
        public int em5_1 { get; set; }
        public int em5_2 { get; set; }
        public int em5_3 { get; set; }
        public int em5_4 { get; set; }
        public int em5_5 { get; set; }
        public string text6_0 { get; set; }
        public string text6_1 { get; set; }
        public int BroadcastTextID6 { get; set; }
        public byte lang6 { get; set; }
        public float prob6 { get; set; }
        public int em6_0 { get; set; }
        public int em6_1 { get; set; }
        public int em6_2 { get; set; }
        public int em6_3 { get; set; }
        public int em6_4 { get; set; }
        public int em6_5 { get; set; }
        public string text7_0 { get; set; }
        public string text7_1 { get; set; }
        public int BroadcastTextID7 { get; set; }
        public byte lang7 { get; set; }
        public float prob7 { get; set; }
        public int em7_0 { get; set; }
        public int em7_1 { get; set; }
        public int em7_2 { get; set; }
        public int em7_3 { get; set; }
        public int em7_4 { get; set; }
        public int em7_5 { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
