//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class page_text
    {
        public int entry { get; set; }
        public string text { get; set; }
        public int next_page { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
