//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet_levelstats
    {
        public int creature_entry { get; set; }
        public byte level { get; set; }
        public int hp { get; set; }
        public int mana { get; set; }
        public long armor { get; set; }
        public int str { get; set; }
        public int agi { get; set; }
        public int sta { get; set; }
        public int inte { get; set; }
        public int spi { get; set; }
    }
}
