//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class playercreateinfo_skills
    {
        public long raceMask { get; set; }
        public long classMask { get; set; }
        public int skill { get; set; }
        public int rank { get; set; }
        public string comment { get; set; }
    }
}
