//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_levelstats
    {
        public byte race { get; set; }
        public byte @class { get; set; }
        public byte level { get; set; }
        public byte str { get; set; }
        public byte agi { get; set; }
        public byte sta { get; set; }
        public byte inte { get; set; }
        public byte spi { get; set; }
    }
}
