//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class points_of_interest
    {
        public int entry { get; set; }
        public float x { get; set; }
        public float y { get; set; }
        public int icon { get; set; }
        public int flags { get; set; }
        public int data { get; set; }
        public string icon_name { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
