//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_poi
    {
        public long questId { get; set; }
        public long id { get; set; }
        public int objIndex { get; set; }
        public long mapid { get; set; }
        public long WorldMapAreaId { get; set; }
        public long FloorId { get; set; }
        public long unk3 { get; set; }
        public long unk4 { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
