//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_template
    {
        public int Id { get; set; }
        public byte Method { get; set; }
        public short Level { get; set; }
        public byte MinLevel { get; set; }
        public byte MaxLevel { get; set; }
        public short ZoneOrSort { get; set; }
        public int Type { get; set; }
        public byte SuggestedPlayers { get; set; }
        public long LimitTime { get; set; }
        public int RequiredClasses { get; set; }
        public int RequiredRaces { get; set; }
        public int RequiredSkillId { get; set; }
        public int RequiredSkillPoints { get; set; }
        public int RequiredFactionId1 { get; set; }
        public int RequiredFactionId2 { get; set; }
        public int RequiredFactionValue1 { get; set; }
        public int RequiredFactionValue2 { get; set; }
        public int RequiredMinRepFaction { get; set; }
        public int RequiredMaxRepFaction { get; set; }
        public int RequiredMinRepValue { get; set; }
        public int RequiredMaxRepValue { get; set; }
        public int PrevQuestId { get; set; }
        public int NextQuestId { get; set; }
        public int ExclusiveGroup { get; set; }
        public int NextQuestIdChain { get; set; }
        public byte RewardXPId { get; set; }
        public int RewardOrRequiredMoney { get; set; }
        public long RewardMoneyMaxLevel { get; set; }
        public int RewardSpell { get; set; }
        public int RewardSpellCast { get; set; }
        public int RewardHonor { get; set; }
        public float RewardHonorMultiplier { get; set; }
        public int RewardMailTemplateId { get; set; }
        public long RewardMailDelay { get; set; }
        public int SourceItemId { get; set; }
        public byte SourceItemCount { get; set; }
        public int SourceSpellId { get; set; }
        public long Flags { get; set; }
        public byte SpecialFlags { get; set; }
        public byte RewardTitleId { get; set; }
        public byte RequiredPlayerKills { get; set; }
        public byte RewardTalents { get; set; }
        public int RewardArenaPoints { get; set; }
        public int RewardItemId1 { get; set; }
        public int RewardItemId2 { get; set; }
        public int RewardItemId3 { get; set; }
        public int RewardItemId4 { get; set; }
        public int RewardItemCount1 { get; set; }
        public int RewardItemCount2 { get; set; }
        public int RewardItemCount3 { get; set; }
        public int RewardItemCount4 { get; set; }
        public int RewardChoiceItemId1 { get; set; }
        public int RewardChoiceItemId2 { get; set; }
        public int RewardChoiceItemId3 { get; set; }
        public int RewardChoiceItemId4 { get; set; }
        public int RewardChoiceItemId5 { get; set; }
        public int RewardChoiceItemId6 { get; set; }
        public int RewardChoiceItemCount1 { get; set; }
        public int RewardChoiceItemCount2 { get; set; }
        public int RewardChoiceItemCount3 { get; set; }
        public int RewardChoiceItemCount4 { get; set; }
        public int RewardChoiceItemCount5 { get; set; }
        public int RewardChoiceItemCount6 { get; set; }
        public int RewardFactionId1 { get; set; }
        public int RewardFactionId2 { get; set; }
        public int RewardFactionId3 { get; set; }
        public int RewardFactionId4 { get; set; }
        public int RewardFactionId5 { get; set; }
        public int RewardFactionValueId1 { get; set; }
        public int RewardFactionValueId2 { get; set; }
        public int RewardFactionValueId3 { get; set; }
        public int RewardFactionValueId4 { get; set; }
        public int RewardFactionValueId5 { get; set; }
        public int RewardFactionValueIdOverride1 { get; set; }
        public int RewardFactionValueIdOverride2 { get; set; }
        public int RewardFactionValueIdOverride3 { get; set; }
        public int RewardFactionValueIdOverride4 { get; set; }
        public int RewardFactionValueIdOverride5 { get; set; }
        public int PointMapId { get; set; }
        public float PointX { get; set; }
        public float PointY { get; set; }
        public int PointOption { get; set; }
        public string Title { get; set; }
        public string Objectives { get; set; }
        public string Details { get; set; }
        public string EndText { get; set; }
        public string OfferRewardText { get; set; }
        public string RequestItemsText { get; set; }
        public string CompletedText { get; set; }
        public int RequiredNpcOrGo1 { get; set; }
        public int RequiredNpcOrGo2 { get; set; }
        public int RequiredNpcOrGo3 { get; set; }
        public int RequiredNpcOrGo4 { get; set; }
        public int RequiredNpcOrGoCount1 { get; set; }
        public int RequiredNpcOrGoCount2 { get; set; }
        public int RequiredNpcOrGoCount3 { get; set; }
        public int RequiredNpcOrGoCount4 { get; set; }
        public int RequiredSourceItemId1 { get; set; }
        public int RequiredSourceItemId2 { get; set; }
        public int RequiredSourceItemId3 { get; set; }
        public int RequiredSourceItemId4 { get; set; }
        public int RequiredSourceItemCount1 { get; set; }
        public int RequiredSourceItemCount2 { get; set; }
        public int RequiredSourceItemCount3 { get; set; }
        public int RequiredSourceItemCount4 { get; set; }
        public int RequiredItemId1 { get; set; }
        public int RequiredItemId2 { get; set; }
        public int RequiredItemId3 { get; set; }
        public int RequiredItemId4 { get; set; }
        public int RequiredItemId5 { get; set; }
        public int RequiredItemId6 { get; set; }
        public int RequiredItemCount1 { get; set; }
        public int RequiredItemCount2 { get; set; }
        public int RequiredItemCount3 { get; set; }
        public int RequiredItemCount4 { get; set; }
        public int RequiredItemCount5 { get; set; }
        public int RequiredItemCount6 { get; set; }
        public byte Unknown0 { get; set; }
        public string ObjectiveText1 { get; set; }
        public string ObjectiveText2 { get; set; }
        public string ObjectiveText3 { get; set; }
        public string ObjectiveText4 { get; set; }
        public int DetailsEmote1 { get; set; }
        public int DetailsEmote2 { get; set; }
        public int DetailsEmote3 { get; set; }
        public int DetailsEmote4 { get; set; }
        public long DetailsEmoteDelay1 { get; set; }
        public long DetailsEmoteDelay2 { get; set; }
        public long DetailsEmoteDelay3 { get; set; }
        public long DetailsEmoteDelay4 { get; set; }
        public int EmoteOnIncomplete { get; set; }
        public int EmoteOnComplete { get; set; }
        public int OfferRewardEmote1 { get; set; }
        public int OfferRewardEmote2 { get; set; }
        public int OfferRewardEmote3 { get; set; }
        public int OfferRewardEmote4 { get; set; }
        public long OfferRewardEmoteDelay1 { get; set; }
        public long OfferRewardEmoteDelay2 { get; set; }
        public long OfferRewardEmoteDelay3 { get; set; }
        public long OfferRewardEmoteDelay4 { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
