//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class random_enchantment
    {
        public int ID { get; set; }
        public int Set { get; set; }
        public int Level { get; set; }
        public int Chance { get; set; }
        public int ClassMask { get; set; }
        public int SubClassMask { get; set; }
        public int InventoryTypeMask { get; set; }
        public int QualityMask { get; set; }
        public string Comment { get; set; }
    }
}
