//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class reputation_reward_rate
    {
        public int faction { get; set; }
        public float quest_rate { get; set; }
        public float quest_daily_rate { get; set; }
        public float quest_weekly_rate { get; set; }
        public float quest_monthly_rate { get; set; }
        public float quest_repeatable_rate { get; set; }
        public float creature_rate { get; set; }
        public float spell_rate { get; set; }
    }
}
