//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class reputation_spillover_template
    {
        public int faction { get; set; }
        public int faction1 { get; set; }
        public float rate_1 { get; set; }
        public byte rank_1 { get; set; }
        public int faction2 { get; set; }
        public float rate_2 { get; set; }
        public byte rank_2 { get; set; }
        public int faction3 { get; set; }
        public float rate_3 { get; set; }
        public byte rank_3 { get; set; }
        public int faction4 { get; set; }
        public float rate_4 { get; set; }
        public byte rank_4 { get; set; }
    }
}
