//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class resource_points
    {
        public long area { get; set; }
        public long max_guard { get; set; }
        public long max_worker { get; set; }
        public long allianceCity1 { get; set; }
        public long allianceResourcePct1 { get; set; }
        public long allianceCity2 { get; set; }
        public long allianceResourcePct2 { get; set; }
        public long allianceCity3 { get; set; }
        public long allianceResourcePct3 { get; set; }
        public long allianceCity4 { get; set; }
        public long allianceResourcePct4 { get; set; }
        public long hordeCity1 { get; set; }
        public long hordeResourcePct1 { get; set; }
        public long hordeCity2 { get; set; }
        public long hordeResourcePct2 { get; set; }
        public long hordeCity3 { get; set; }
        public long hordeResourcePct3 { get; set; }
        public long hordeCity4 { get; set; }
        public long hordeResourcePct4 { get; set; }
        public string scriptname { get; set; }
        public string comment { get; set; }
    }
}
