//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_dbc
    {
        public long Id { get; set; }
        public long Dispel { get; set; }
        public long Mechanic { get; set; }
        public long Attributes { get; set; }
        public long AttributesEx { get; set; }
        public long AttributesEx2 { get; set; }
        public long AttributesEx3 { get; set; }
        public long AttributesEx4 { get; set; }
        public long AttributesEx5 { get; set; }
        public long AttributesEx6 { get; set; }
        public long AttributesEx7 { get; set; }
        public long Stances { get; set; }
        public long StancesNot { get; set; }
        public long Targets { get; set; }
        public long CastingTimeIndex { get; set; }
        public long AuraInterruptFlags { get; set; }
        public long ProcFlags { get; set; }
        public long ProcChance { get; set; }
        public long ProcCharges { get; set; }
        public long MaxLevel { get; set; }
        public long BaseLevel { get; set; }
        public long SpellLevel { get; set; }
        public long DurationIndex { get; set; }
        public long RangeIndex { get; set; }
        public long StackAmount { get; set; }
        public int EquippedItemClass { get; set; }
        public int EquippedItemSubClassMask { get; set; }
        public int EquippedItemInventoryTypeMask { get; set; }
        public long Effect1 { get; set; }
        public long Effect2 { get; set; }
        public long Effect3 { get; set; }
        public int EffectDieSides1 { get; set; }
        public int EffectDieSides2 { get; set; }
        public int EffectDieSides3 { get; set; }
        public float EffectRealPointsPerLevel1 { get; set; }
        public float EffectRealPointsPerLevel2 { get; set; }
        public float EffectRealPointsPerLevel3 { get; set; }
        public int EffectBasePoints1 { get; set; }
        public int EffectBasePoints2 { get; set; }
        public int EffectBasePoints3 { get; set; }
        public long EffectMechanic1 { get; set; }
        public long EffectMechanic2 { get; set; }
        public long EffectMechanic3 { get; set; }
        public long EffectImplicitTargetA1 { get; set; }
        public long EffectImplicitTargetA2 { get; set; }
        public long EffectImplicitTargetA3 { get; set; }
        public long EffectImplicitTargetB1 { get; set; }
        public long EffectImplicitTargetB2 { get; set; }
        public long EffectImplicitTargetB3 { get; set; }
        public long EffectRadiusIndex1 { get; set; }
        public long EffectRadiusIndex2 { get; set; }
        public long EffectRadiusIndex3 { get; set; }
        public long EffectApplyAuraName1 { get; set; }
        public long EffectApplyAuraName2 { get; set; }
        public long EffectApplyAuraName3 { get; set; }
        public int EffectAmplitude1 { get; set; }
        public int EffectAmplitude2 { get; set; }
        public int EffectAmplitude3 { get; set; }
        public float EffectMultipleValue1 { get; set; }
        public float EffectMultipleValue2 { get; set; }
        public float EffectMultipleValue3 { get; set; }
        public long EffectItemType1 { get; set; }
        public long EffectItemType2 { get; set; }
        public long EffectItemType3 { get; set; }
        public int EffectMiscValue1 { get; set; }
        public int EffectMiscValue2 { get; set; }
        public int EffectMiscValue3 { get; set; }
        public int EffectMiscValueB1 { get; set; }
        public int EffectMiscValueB2 { get; set; }
        public int EffectMiscValueB3 { get; set; }
        public long EffectTriggerSpell1 { get; set; }
        public long EffectTriggerSpell2 { get; set; }
        public long EffectTriggerSpell3 { get; set; }
        public long EffectSpellClassMaskA1 { get; set; }
        public long EffectSpellClassMaskA2 { get; set; }
        public long EffectSpellClassMaskA3 { get; set; }
        public long EffectSpellClassMaskB1 { get; set; }
        public long EffectSpellClassMaskB2 { get; set; }
        public long EffectSpellClassMaskB3 { get; set; }
        public long EffectSpellClassMaskC1 { get; set; }
        public long EffectSpellClassMaskC2 { get; set; }
        public long EffectSpellClassMaskC3 { get; set; }
        public long MaxTargetLevel { get; set; }
        public long SpellFamilyName { get; set; }
        public long SpellFamilyFlags1 { get; set; }
        public long SpellFamilyFlags2 { get; set; }
        public long SpellFamilyFlags3 { get; set; }
        public long MaxAffectedTargets { get; set; }
        public long DmgClass { get; set; }
        public long PreventionType { get; set; }
        public float DmgMultiplier1 { get; set; }
        public float DmgMultiplier2 { get; set; }
        public float DmgMultiplier3 { get; set; }
        public int AreaGroupId { get; set; }
        public long SchoolMask { get; set; }
        public string Comment { get; set; }
    }
}
