//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_enchant_proc_data
    {
        public long entry { get; set; }
        public long customChance { get; set; }
        public float PPMChance { get; set; }
        public long procEx { get; set; }
    }
}
