//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_area
    {
        public int spell { get; set; }
        public int area { get; set; }
        public int quest_start { get; set; }
        public int quest_end { get; set; }
        public int aura_spell { get; set; }
        public int racemask { get; set; }
        public byte gender { get; set; }
        public byte autocast { get; set; }
        public int quest_start_status { get; set; }
        public int quest_end_status { get; set; }
    }
}
