//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_accessory
    {
        public int guid { get; set; }
        public int accessory_entry { get; set; }
        public sbyte seat_id { get; set; }
        public byte minion { get; set; }
        public string description { get; set; }
        public byte summontype { get; set; }
        public long summontimer { get; set; }
    }
}
