//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class warden_checks
    {
        public int id { get; set; }
        public Nullable<byte> type { get; set; }
        public string data { get; set; }
        public string str { get; set; }
        public Nullable<long> address { get; set; }
        public Nullable<byte> length { get; set; }
        public string result { get; set; }
        public string comment { get; set; }
    }
}
