//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSAToolBox
{
    using System;
    using System.Collections.Generic;
    
    public partial class waypoint_data
    {
        public long id { get; set; }
        public int point { get; set; }
        public float position_x { get; set; }
        public float position_y { get; set; }
        public float position_z { get; set; }
        public float orientation { get; set; }
        public long delay { get; set; }
        public int move_type { get; set; }
        public int action { get; set; }
        public short action_chance { get; set; }
        public int wpguid { get; set; }
    }
}
